// <auto-generated />
using System;
using E_Commerce_Platform_Ass1.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_Platform_Ass1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117061619_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "InActive",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductVariantId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ProductVariantId1");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            CartId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            ProductVariantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            CartId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            ProductVariantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            CartId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            ProductVariantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Name = "Glasses",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("20202020-2020-2020-2020-202020202020"),
                            Name = "Contact Lens",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("30303030-3030-3030-3030-303030303030"),
                            Name = "Accessories",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "HCM",
                            Status = "Paid",
                            TotalAmount = 1200000m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "Hanoi",
                            Status = "Pending",
                            TotalAmount = 700000m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddress = "Danang",
                            Status = "Delivered",
                            TotalAmount = 150000m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("order_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            OrderId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Price = 1200000m,
                            ProductName = "Rayban Black M",
                            ProductVariantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000002"),
                            OrderId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Price = 350000m,
                            ProductName = "Acuvue Lens",
                            ProductVariantId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000003"),
                            OrderId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Price = 150000m,
                            ProductName = "Glasses Case",
                            ProductVariantId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("TransactionCode")
                        .IsUnique();

                    b.ToTable("payments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000001"),
                            Amount = 1200000m,
                            Method = "VNPay",
                            OrderId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            PaidAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "Success",
                            TransactionCode = "TXN001"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000002"),
                            Amount = 700000m,
                            Method = "Momo",
                            OrderId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            PaidAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TransactionCode = "TXN002"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000003"),
                            Amount = 150000m,
                            Method = "Momo",
                            OrderId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            PaidAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "Success",
                            TransactionCode = "TXN003"
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AvgRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.HasIndex("ShopId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            AvgRating = 4.5m,
                            BasePrice = 1200000m,
                            CategoryId = new Guid("10101010-1010-1010-1010-101010101010"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Men Glasses",
                            ImageUrl = "rayban.png",
                            Name = "Rayban Glasses",
                            ShopId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("bbbb2222-2222-2222-2222-222222222222"),
                            AvgRating = 4.7m,
                            BasePrice = 350000m,
                            CategoryId = new Guid("20202020-2020-2020-2020-202020202020"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Monthly Lens",
                            ImageUrl = "acuvue.png",
                            Name = "Acuvue Lens",
                            ShopId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("cccc3333-3333-3333-3333-333333333333"),
                            AvgRating = 4.2m,
                            BasePrice = 150000m,
                            CategoryId = new Guid("30303030-3030-3030-3030-303030303030"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Leather Case",
                            ImageUrl = "case.png",
                            Name = "Glasses Case",
                            ShopId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("ProductId", "Size", "Color")
                        .IsUnique()
                        .HasFilter("[Size] IS NOT NULL AND [Color] IS NOT NULL");

                    b.ToTable("product_variants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Color = "Black",
                            ImageUrl = "rb-black.png",
                            Price = 1200000m,
                            ProductId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            Size = "M",
                            Sku = "RB-BLK-M",
                            Status = "Active",
                            Stock = 10,
                            VariantName = "Black-M"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Color = "Clear",
                            ImageUrl = "acu-clear.png",
                            Price = 350000m,
                            ProductId = new Guid("bbbb2222-2222-2222-2222-222222222222"),
                            Size = "Standard",
                            Sku = "ACU-CLR",
                            Status = "Active",
                            Stock = 50,
                            VariantName = "Clear"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Color = "Brown",
                            ImageUrl = "case-brown.png",
                            Price = 150000m,
                            ProductId = new Guid("cccc3333-3333-3333-3333-333333333333"),
                            Size = "Standard",
                            Sku = "CASE-BR",
                            Status = "Active",
                            Stock = 30,
                            VariantName = "Brown"
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModeratedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModerationReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<decimal>("SpamScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ToxicityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("reviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Comment = "Great!",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            ModeratedBy = new Guid("55554444-5555-5555-5555-555555555555"),
                            ModerationReason = "",
                            OrderItemId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("aaaa1111-1111-1111-1111-111111111111"),
                            Rating = 5,
                            SpamScore = 0m,
                            Status = "Approved",
                            ToxicityScore = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Comment = "Good lens",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            ModeratedBy = new Guid("55554444-5555-5555-5555-555555555555"),
                            ModerationReason = "",
                            OrderItemId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("bbbb2222-2222-2222-2222-222222222222"),
                            Rating = 4,
                            SpamScore = 0m,
                            Status = "Approved",
                            ToxicityScore = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Comment = "Nice case",
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            ModeratedBy = new Guid("55554444-5555-5555-5555-555555555555"),
                            ModerationReason = "",
                            OrderItemId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("cccc3333-3333-3333-3333-333333333333"),
                            Rating = 5,
                            SpamScore = 0m,
                            Status = "Approved",
                            ToxicityScore = 0m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("99999999-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Normal customer",
                            Name = "Customer"
                        },
                        new
                        {
                            RoleId = new Guid("99999999-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shop owner",
                            Name = "Shop"
                        },
                        new
                        {
                            RoleId = new Guid("99999999-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "System administrator",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.ToTable("shipments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000001"),
                            Carrier = "GHTK",
                            OrderId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Status = "Delivering",
                            TrackingCode = "TRK001",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000002"),
                            Carrier = "VNPost",
                            OrderId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Status = "Pending",
                            TrackingCode = "TRK002",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000003"),
                            Carrier = "GHN",
                            OrderId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Status = "Delivered",
                            TrackingCode = "TRK003",
                            UpdatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShopName")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("shops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Eyewear Shop",
                            ShopName = "Vision Store",
                            Status = "Active",
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Contact Lens",
                            ShopName = "Lens World",
                            Status = "Active",
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Optic Accessories",
                            ShopName = "Optic Pro",
                            Status = "Active",
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "a@mail.com",
                            Name = "Customer A",
                            PasswordHash = "$2a$11$tVSQZ.QyXTekMK9jnqwhWuM69Hnwiubpy1whI.uLRR4.HYRaJPwwC",
                            RoleId = new Guid("99999999-1111-1111-1111-111111111111"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "shopA@mail.com",
                            Name = "Shop Owner A",
                            PasswordHash = "$2a$11$tVSQZ.QyXTekMK9jnqwhWuM69Hnwiubpy1whI.uLRR4.HYRaJPwwC",
                            RoleId = new Guid("99999999-2222-2222-2222-222222222222"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "shopB@mail.com",
                            Name = "Shop Owner B",
                            PasswordHash = "$2a$11$tVSQZ.QyXTekMK9jnqwhWuM69Hnwiubpy1whI.uLRR4.HYRaJPwwC",
                            RoleId = new Guid("99999999-2222-2222-2222-222222222222"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "shopC@mail.com",
                            Name = "Shop Owner C",
                            PasswordHash = "$2a$11$tVSQZ.QyXTekMK9jnqwhWuM69Hnwiubpy1whI.uLRR4.HYRaJPwwC",
                            RoleId = new Guid("99999999-2222-2222-2222-222222222222"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("55554444-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "mod@mail.com",
                            Name = "Moderator",
                            PasswordHash = "$2a$11$tVSQZ.QyXTekMK9jnqwhWuM69Hnwiubpy1whI.uLRR4.HYRaJPwwC",
                            RoleId = new Guid("99999999-3333-3333-3333-333333333333"),
                            Status = true
                        });
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Cart", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.User", null)
                        .WithMany("Carts")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.CartItem", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.ProductVariant", null)
                        .WithMany("CartItems")
                        .HasForeignKey("ProductVariantId1");

                    b.Navigation("Cart");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Order", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.OrderItem", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.ProductVariant", "ProductVariant")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Payment", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Product", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.ProductVariant", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Review", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.OrderItem", "OrderItem")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.User", null)
                        .WithMany("Reviews")
                        .HasForeignKey("UserId1");

                    b.Navigation("OrderItem");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Shipment", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Shop", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("E_Commerce_Platform_Ass1.Data.Database.Entities.Shop", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.User", b =>
                {
                    b.HasOne("E_Commerce_Platform_Ass1.Data.Database.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.OrderItem", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Product", b =>
                {
                    b.Navigation("ProductVariants");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.Shop", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_Commerce_Platform_Ass1.Data.Database.Entities.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
